name: Maven build

on:
  push:
    branches: [ development ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Alert Message
        run: echo "Running Maven tests"
        
      - name: Run build
        run: mvn clean install
