name: Maven test & Docker build-push

on:
  push:
    branches: [ development ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set SHA8
      run: echo ::set-env name=SHA8::$(git log --oneline -1 | awk '{print $1}')

    - name: Test SHA8
      run: echo $SHA8

    - name: Set up JDK 11
      uses: actions/setup-java@v1.4.2
      with:
        java-version: '11.0.8'

    - name: Build with Maven
      run: mvn clean install

    - name: Login to GitHub Registry Container
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Create docker loadbalancer image
      run: docker build -t ghcr.io/mattrighetti/loadbalancer:latest -t ghcr.io/mattrighetti/loadbalancer:$SHA8 ./loadbalancer

    - name: Create docker cluster_node image
      run: docker build -t ghcr.io/mattrighetti/cluster_node:latest -t ghcr.io/mattrighetti/cluster_node:$SHA8 ./cluster

    - name: Push docker images
      run: |
        docker push ghcr.io/mattrighetti/loadbalancer:latest
        docker push ghcr.io/mattrighetti/loadbalancer:$SHA8
        docker push ghcr.io/mattrighetti/cluster_node:latest
        docker push ghcr.io/mattrighetti/cluster_node:$SHA8